app:
  name: annotation
  port: 3030
  env: local

mysql:
  host: localhost
  port: 3306
  username: root
  password: 123456
  database: annotation

redis:
  host: localhost
  port: 6379
  password:
  db: 0